name: 'Converting SVG code to png'
inputs:
  file:
    description: 'file path to convert the SVG code'
    required: true
    default: 'README.md'
runs:
  using: 'composite'
  steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install cairosvg package
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          cairosvg
    - name: Execute python script to converts
      shell: bash
      run: python ${{ github.action_path }}/svg-to-png.py ${{ inputs.file }}